#!/bin/sh
# Compile:by-lanse    2018-08-28

echo -e "\e[1;36m 下载 Fq 翻网规则 \e[0m\n"
TMP_FQ=/tmp/tmp_fq
TMP_FQ2=/tmp/tmp_fq2
TMP_FQ3=/tmp/tmp_fq3
FQ=/tmp/fq

[ -f ${FQ} ] && rm -rf ${FQ};[ -f ${TMP_FQ2} ] && rm -rf ${TMP_FQ2};[ -f ${TMP_FQ3} ] && rm -rf ${TMP_FQ3}
for URL in \
	"https://raw.githubusercontent.com/sy618/hosts/master/data/yahoo" \
	"https://raw.githubusercontent.com/sy618/hosts/master/data/tumblr"
do
	wget --no-check-certificate -t 15 -T 50 -O- "${URL}" \
	| awk '$1 ~ /^[0-9]/ {printf("address=/%s/%s\n", $2,$1)}' >> ${TMP_FQ}
done

wget --no-check-certificate -t 15 -T 50 -O- "https://raw.githubusercontent.com/sy618/hosts/master/dnsmasq/dnsfq" \
|sed -E -e "/# /d" -e "/\#a/d" -e "/^$/d" -e "/★/d" -e "/^#/d" -e "/^$/d" >> ${TMP_FQ2}

wget --no-check-certificate -t 15 -T 50 -O- "https://raw.githubusercontent.com/896660689/Hsfq/master/hs_pc" \
| sed -E -e "/#/d" >> ${TMP_FQ3}

sed -i "/youtube/d; /tumblr/d" ${TMP_FQ2}

#wget --no-check-certificate -t 20 -T 60 -O- "http://idannywu.com/dannywugooglehosts/noadhosts.txt" \
#| awk '{if(/^#/||/^$/) {print $0} else {print "address=/"$2"/"$1"\t"$3,"\n""address=/"$2"/#"}}' \
#| sed -E -e "/#/d" -e "/^$/d" -e "/::/d" -e "/localhos/d" >> ${TMP_FQ4}

sleep 2
cat ${TMP_FQ3} ${TMP_FQ2} ${TMP_FQ} > ${FQ}

echo -e "\033[45;37m 翻网规则下载完成 \033[0m\n"
# 删除临时缓存
rm -rf ${TMP_FQ2} ${TMP_FQ3} ${TMP_FQ} 2> /dev/null
